### ISSUE TITLE
i'm press ctrl+f5 in window app.config  i's program don't run 

### ISSUE THREAD

**Issue by iverymes01** [NecronomiconCoding/Pokemon-Go-Rocket-API#15]

**Comment by Velorianvx77** [comment]
Same issue.  Nothing happens when pushing ctrl + F5 after editting the app.config.  I have the app.config open and I push ctrl + F5.  I have Visual Studio 2015, do I need a different version? Do I need a completely different environment open?  Slightly confused, please help.
