### ISSUE TITLE
Bug: Stops after 5 minutes

### ISSUE THREAD

**Issue by CherryLoveSCM** [NecronomiconCoding/Pokemon-Go-Rocket-API#16]
so this happened I start it everything works fine then after ~5 minutes it stops printing text and I have to restart it. Happened everytime I've tried "reinstalling"/ re setup 

On the screenshot you can see it stopped at 05:45 I believe and now the clock is 06:16
![image](https://cloud.githubusercontent.com/assets/8770436/17011110/874344aa-4f0a-11e6-9273-cc8ec581bfb3.jpeg)

**Comment by Velorianvx77** [comment]
What do you have activated in the app.config? I noticed I can't even connect if I have Evolve Pokemon on and I dont have any pokemon to evolve.

**Comment by murdick** [comment]
I am seeing the same problem on my windows 10 and windows 7 test machine.

**Comment by CherryLoveSCM** [comment]
Well it's on a Windows 8.1 and I'm only using transfer but I've tried without also

**Comment by Hardell** [comment]
Try a more populated location. It might be because it gets stuck in a place with nothing around?

**Comment by CherryLoveSCM** [comment]
Yeah that maybe the cause will try a bigger city now will post when I see if it works or not

**Comment by Hardell** [comment]
Yeah, let me know if it works. Thanks.

**Comment by CherryLoveSCM** [comment]
Thank you Hardell it's now working completely fine! :D 
Hardell your the type of person you want in life helping other very good! Love you
