### ISSUE TITLE
Catch All Pokemons

### ISSUE THREAD

**Issue by Imperator26** [NecronomiconCoding/Pokemon-Go-Rocket-API#23]
So I've removed the comment from
` await ExecuteCatchAllNearbyPokemons(client);`
which I guess should let the bot catch every pokemon that shows up. Instead I still get messages like:

> Magikarp with CP 17 got away..

**Comment by Imperator26** [comment]
I looked the C# `await` up and I believe that I should comment this `await ExecuteFarmingPokestopsAndPokemons(client);` if I want to make the other work

**Comment by Hardell** [comment]
ExecuteCatchAllNearbyPokemons is included in ExecuteFarmingPokestopsAndPokemons. You don't need to uncomment the other one.

If all your pokemon escape you're banned for a while. If some of them escape every now and then, it happens.
