### ISSUE TITLE
Only Google loginc possible, PTC ignored

### ISSUE THREAD

**Issue by RedNax67** [NecronomiconCoding/Pokemon-Go-Rocket-API#25]
With the latest token commit, i can't login with a ptc account..... It'll just show the "Please visit https://www.google.com/device and enter..." message

**Comment by Hardell** [comment]
Can you check your config file? You probably redownloaded the entire thing and the default log in option is Google.

**Comment by RedNax67** [comment]
I did redownload the whole thing, however i've also added Ptc as AuthType and a username/passwd pair..

Google is the default athtype when it doesn't recogise Ptc... so my feeling is it doesn't read the app.config

**Comment by Hardell** [comment]
It seems to be working for me. Did you write it exactly as "Ptc" with a capital P?

**Comment by RedNax67** [comment]
Yup, even copy/pasted it from the remark...
I'll have a go at a fresh download...

**Comment by DeirhX** [comment]
I just successfully used it for Ptc login via app.config. So no problem there.

**Comment by RedNax67** [comment]
<add key="AuthType" value="Ptc"/> 
<add key="PtcUsername" value="xxxxxxxxx"/>
<add key="PtcPassword" value="xxxxxxxxxx"/>

New install/build.. no joy...
/i'll revert to the previous version an start from there..

**Comment by RedNax67** [comment]
After the most recent commit  11177e0 it works again for me..... case closed.. for now ;)
