### ISSUE TITLE
game crash after like 15-30 minutes

### ISSUE THREAD

**Issue by Luc4z** [NecronomiconCoding/Pokemon-Go-Rocket-API#27]
with PTC login , so wierd

**Comment by neorm** [comment]
![error](https://cloud.githubusercontent.com/assets/9902367/17021324/8ec3f7e6-4f47-11e6-92ad-93661a761842.jpg)

not sure if that is the same problem, but for me it works for about 30 min.

**Comment by Hardell** [comment]
I just pushed an update, it should restart after crashing now. Let me know if it works for you.

**Comment by Luc4z** [comment]
thanks and ill try it , btw why this happened ?

**Comment by neorm** [comment]
ok, will give a update soon

**Comment by neorm** [comment]
Ok, it works now. Great work, keep going. Looks awesome so far
