### ISSUE TITLE
null reference

### ISSUE THREAD

**Issue by Anybal** [NecronomiconCoding/Pokemon-Go-Rocket-API#30]
null reference in log app and do nothing after.

**Comment by Hardell** [comment]
Can you check if you entered your username and password correctly? I'm working on a fix and it seems we get this exception when it can't log in with the username and password you set in app.config.

**Comment by Anybal** [comment]
I change my username et password for an other account (i know he work with other bot), and now, he crash after do nothing. No null reference atm, just crashing.

**Comment by Anybal** [comment]
Ok he's work for me now :) thank you a lot
