### ISSUE TITLE
Getting the Level of a Player

### ISSUE THREAD

**Issue by Yixn** [NecronomiconCoding/Pokemon-Go-Rocket-API#33]
Is it possible to get the Player's Level via the PlayerStats in Inventory?

I tried a few things, but i think im too inexperienced with c#.

Any Help would be appreciated

**Comment by CherryLoveSCM** [comment]
http://hackforums.net/showthread.php?tid=5345302&pid=51756533#pid51756533

Yeah a guy already made it here^
You might have to sign up to view it not to sure

**Comment by Yixn** [comment]
Thank you very much, that really helped :D
