### ISSUE TITLE
Can it transfer pokemon right after we caught it ?

### ISSUE THREAD

**Issue by Luc4z** [NecronomiconCoding/Pokemon-Go-Rocket-API#34]
and of course i'd active save highest cp one , thanks !

so we don't need to open the program again to let it sell it

**Comment by Hardell** [comment]
It does it already.

**Comment by Luc4z** [comment]
i tested and it won't transter right after caught in "leaveStrongest" mode , it only transfer them when i open this program again , because i still saw the Grinding list while i open the game .

and the program stop at 20 minutes without any error message and i just top
