### ISSUE TITLE
firing up the meat finder is too often

### ISSUE THREAD

**Issue by neorm** [NecronomiconCoding/Pokemon-Go-Rocket-API#35]
Hi, after the last update the the meatfinder ist tring to Transfer pokemons even if there was no catch. That was some time in my oppinion.

 [!] firing up the meat grinder
Grinding 0 pokemon below 225 CP.
[!] finished grinding all the meat
[15:52:18] Farmed XP: 50, Gems: 0, Eggs:  Items: 1 x ItemGreatBall, 2 x ItemRazzBerry
[!] firing up the meat grinder
Grinding 0 pokemon below 225 CP.
[!] finished grinding all the meat
[15:52:29] Farmed XP: 50, Gems: 0, Eggs:  Items: 1 x ItemPokeBall, 1 x ItemGreatBall, 1 x ItemRazzBerry
[!] firing up the meat grinder
Grinding 0 pokemon below 225 CP.
[!] finished grinding all the meat
[15:52:41] Farmed XP: 0, Gems: 0, Eggs:  Items:
[!] firing up the meat grinder
Grinding 0 pokemon below 225 CP.
[!] finished grinding all the meat
[15:52:52] Farmed XP: 50, Gems: 0, Eggs:  Items: 3 x ItemPokeBall
[!] firing up the meat grinder
Grinding 0 pokemon below 225 CP.
[!] finished grinding all the meat
[15:53:03] Farmed XP: 50, Gems: 0, Eggs:  Items: 1 x ItemHyperPotion, 1 x ItemPotion, 1 x ItemRazzBerry

**Comment by GamespikeYT** [comment]
yeah i added a comment to 'suggestion: transfer after catch' reffering to another api where i saw it only transfer the pokemon you just caught if it was lower than the one you allready had and if it was on a list.

**Comment by neorm** [comment]
it would be nice if it would start grinding afer if catched 10 pokemons or so. In this case you would not lose so much time.

**Comment by Hardell** [comment]
I've just reduced the spam for some transfer types for now. I'll rewrite the entire transferring later

**Comment by neorm** [comment]
ty

**Comment by GamespikeYT** [comment]
thanks man :) keep up the good word :D
