### ISSUE TITLE
What type of Pokeball used

### ISSUE THREAD

**Issue by mich3lam** [NecronomiconCoding/Pokemon-Go-Rocket-API#36]
Logger.Write(caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchSuccess ? $"We caught a {pokemon.PokemonId} with CP {encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp} using a {pokeball}" : 

Not possible since {pokeball} not configured i guess. how can we do that?

**Comment by Krexis** [comment]
Maybe a CP threshold for certain balls. -500: Regular +500: Greatball so on.

**Comment by shejk0** [comment]
It's there already.
Client.cp
`            if (masterBallsCount > 0 && pokemonCP >= 1000)
                return MiscEnums.Item.ITEM_MASTER_BALL;

            if (ultraBallsCount > 0 && pokemonCP >= 600)
                return MiscEnums.Item.ITEM_ULTRA_BALL;

            if (greatBallsCount > 0 && pokemonCP >= 350)
                return MiscEnums.Item.ITEM_GREAT_BALL;

            // If low CP pokemon, but no more pokeballs; only use better balls if pokemon are of semi-worthy quality
            if (pokeBallsCount > 0)
                return MiscEnums.Item.ITEM_POKE_BALL;
            else if ((greatBallsCount < 40 && greatBallsCount > 0 && pokemonCP >= 200) || greatBallsCount >= 40)
                return MiscEnums.Item.ITEM_GREAT_BALL;
            else if (ultraBallsCount > 0 && pokemonCP >= 500)
                return MiscEnums.Item.ITEM_ULTRA_BALL;
            else if (masterBallsCount > 0 && pokemonCP >= 700)
                return MiscEnums.Item.ITEM_MASTER_BALL;`
