### ISSUE TITLE
Meat Grinder

### ISSUE THREAD

**Issue by Krexis** [NecronomiconCoding/Pokemon-Go-Rocket-API#37]
Have latest version, just recently downloaded.
![53a3c765a2b64b8c83c4cf6bfa127178](https://cloud.githubusercontent.com/assets/20580651/17026162/c581185e-4f24-11e6-8fc4-c8aefe708734.png)
Keeps spamming the meat grinder over and over.

**Comment by Hardell** [comment]
I'll fix this, 1 second.

**Comment by Hardell** [comment]
Done. Shouldn't print anything if there isn't anything to grind now.
