### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by Velorianvx77** [NecronomiconCoding/Pokemon-Go-Rocket-API#38]
1>E:\Helpful Software\Pokemon-Go-Rocket-API-master\PokemonGo\RocketAPI\Console\Program.cs(143,42,143,45): warning CS0168: The variable 'tce' is declared but never used
1>E:\Helpful Software\Pokemon-Go-Rocket-API-master\PokemonGo\RocketAPI\Console\Program.cs(144,39,144,42): warning CS0168: The variable 'ufe' is declared but never used
1>E:\Helpful Software\Pokemon-Go-Rocket-API-master\PokemonGo\RocketAPI\Console\Program.cs(145,48,145,52): warning CS0168: The variable 'aore' is declared but never used
1>E:\Helpful Software\Pokemon-Go-Rocket-API-master\PokemonGo\RocketAPI\Console\Program.cs(146,43,146,46): warning CS0168: The variable 'nre' is declared but never used
1>E:\Helpful Software\Pokemon-Go-Rocket-API-master\PokemonGo\RocketAPI\Console\Program.cs(190,36,190,48): error CS1501: No overload for method 'CatchPokemon' takes 6 arguments
1>E:\Helpful Software\Pokemon-Go-Rocket-API-master\PokemonGo\RocketAPI\Console\Program.cs(205,17,205,24): warning CS0219: The variable 'counter' is assigned but its value is never used

**Comment by Hardell** [comment]
These are warnings, I'll fix them in the next push.
