### ISSUE TITLE
Can we use better ball when pokemon got higher CP ?

### ISSUE THREAD

**Issue by Luc4z** [NecronomiconCoding/Pokemon-Go-Rocket-API#39]
like use great ball when i over 250 and ultra 500 etc .

i know there's a guy did it can you guys make it happen ? if you need i can give you guys his Github , he's OP too , thanks ! @Hardell

**Comment by Hardell** [comment]
It already uses great balls on pokemon with 250+CP if it has enough of them. I'll move the PC threshold to settings sometime soon so that everyone can set whatever they want.

**Comment by Luc4z** [comment]
thanks man , you guys op op , i didn't see ball using message so i thought it didnt in it , maybe you guys can put some ball usage message and item delete in it , thanks !

**Comment by Luc4z** [comment]
@Hardell thanks again , this one is better than the others now , and nice frequently update
