### ISSUE TITLE
It wont transfer right after cause in "leaveStrongest" mode

### ISSUE THREAD

**Issue by Luc4z** [NecronomiconCoding/Pokemon-Go-Rocket-API#44]
i tested and it won't transter right after caught in "leaveStrongest" mode , it only transfer them when i open this program again , because i still saw the Grinding list while i open the game .

and the program stop at 20 minutes without any error message and i just top .

or it only active in another mode like CP mode ?

**Comment by Hardell** [comment]
Download the latest version. That one grinds regularly.

I'll fix the other bug where it stops.

**Comment by Luc4z** [comment]
thanks senpai ! hope you saw another mention in solved sector
