### ISSUE TITLE
Not using better balls

### ISSUE THREAD

**Issue by Krexis** [NecronomiconCoding/Pokemon-Go-Rocket-API#51]
I saw you said it was using better balls for 250+ cp

![bfcda1c2a51ea7bfec8fe0fa2dbcf6e9](https://cloud.githubusercontent.com/assets/20580651/17029325/71b5cc18-4f30-11e6-8528-09af86eb2937.png)

**Comment by shejk0** [comment]
from 350cp+

**Comment by xDiglett** [comment]
This is the current logic for using pokeballs:
```csharp
// Use better balls for high CP pokemon
if (masterBallsCount > 0 && pokemonCP >= 1000)
    return MiscEnums.Item.ITEM_MASTER_BALL;

if (ultraBallsCount > 0 && pokemonCP >= 600)
    return MiscEnums.Item.ITEM_ULTRA_BALL;

if (greatBallsCount > 0 && pokemonCP >= 350)
    return MiscEnums.Item.ITEM_GREAT_BALL;
```

**Comment by Krexis** [comment]
Alright, thanks I noticed I was missing ALOT of higher cp pokemon, just unlucky I guess.
