### ISSUE TITLE
Save/Merge App.config 

### ISSUE THREAD

**Issue by Ehnoah** [NecronomiconCoding/Pokemon-Go-Rocket-API#7]
If you update via SVN then App.config conflicts for me. We / you should may ignore the File in Pushes?

**Comment by shejk0** [comment]
I think you can add the file to ignore list and update by yourself when it's necessary.
https://scr.hu/YO03WN

**Comment by Hardell** [comment]
It's probably because you changed your username/pwd or other values that aren't in the repo. If not, I don't know why get conflicts, I don't get any.
If we add the file to the ignore list we won't be able to push changes to the structure of the config.
